"use strict";
exports.__esModule = true;
var message = "Goodbye Everybody";
console.log(message);
var sum;
var title = 'tutorial';
var isbeginner = true;
var total = 0;
var name = 'iets';
var sentence = "dit wordt " + name + "\ndit is mijn eerste Typescript";
console.log(sentence);
var n = null;
var u = undefined;
var isNew = null;
var Myname = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ['Bob', 22];
var Color;
(function (Color) {
    Color[Color["Red"] = 5] = "Red";
    Color[Color["Green"] = 6] = "Green";
    Color[Color["Blue"] = 7] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
